# Build tagged versions of the reference implementation compiler
name: Build the compiler

on:
  push:
    branches: ["complete-test-suite"]
  # Only trigger manually
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        # just ubuntu for now, add macos later
        os: [ubuntu-latest]
        # just a couple of tags for now, add more later
        tag: [2, 16]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # check out nqcc-ref-impl at specific tag
      - uses: actions/checkout@v3
        with:
          repository: nlsandler/nqcc-ref-impl
          ref: ${{ matrix.tag }}
          token: ${{ secrets.NQCC_PAT }}
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
